theme:
    active: Gray
    banner: LightGreen
    error_border: Red
    error_text: LightRed
    hint: LightGreen
    hovered: "255, 255, 255"
    inactive: Gray
    playbar_background: Black
    playbar_progress: "29, 185, 84"
    text: "255, 255, 255"

keybindings:
    increasse_volume: "="

behavior:
    seek_milliseconds: 5000
    volume_increment: 5
    tick_rate_milliseconds: 50
